### ISSUE TITLE
8글자 제한 풀어주세요

### ISSUE THREAD

**Issue by chuhoJun** [yoonjoohye/mandal-art#45]
영문 8글자
한글 8글자
더 입력할수 있게 해주세요.

**Comment by yoonjoohye** [comment]
@chuhoJun 
안녕하세요.
일단 먼저 관심 가져주셔서 너무너무 감사합니다. 😊
입력칸마다 총 24글자까지 적을 수 있도록 수정했습니다.
다른 피드백도 언제나 환영입니다!
