### ISSUE TITLE
Vertical align middle 

### ISSUE THREAD

**Issue by chuhoJun** [yoonjoohye/mandal-art#48]
24글자 확대이후
첫줄만 입력하는 경우 테이블 위로 정렬 됩니다.
중간 정렬(Vertical align middle) 적용 부탁드립니다.

**Comment by yoonjoohye** [comment]
@chuhoJun  
안녕하세요,

본론을 먼저 말씀드리자면, vertical-align:middle은 textarea에 지원되지 않습니다.😢 

몇달 전부터 이런 문제를 예측하고 있었지만, 어떻게 해야할지 정말 고민을 많이 했습니다. 
처음에는 예쁘게 보이는 것을 택했고, input 태그로 8글자로 제한을 뒀지만, 저번 피드백을 듣고 textarea를 변경하여 여러줄을 작성하게끔 했습니다.

 textarea에서 그나마 중앙정렬인 것처럼 보이게 하려면 아래와 같은 방법으로 사용해야합니다.
1. padding 값을 줘서 맞춘다.
2. line-height로 다이나믹하게 맞춘다.

첫번째의 경우, padding 값을 줘서 중간 정렬되어있는 것처럼 보이게 하는 것입니다. 
이미 그렇게 만들어서 배포했지만, 말씀하신걸로 보아 전혀 중앙정렬인것 처럼 보이지 않나봅니다.😭

두번째의 경우, 첫줄 또는 10글자 미만일때  line-height를 주어 가운데로 정렬되어있는 것처럼 보이게 하는 것입니다. 이번에는 두번째 방법으로 만들어 배포했지만, 이것 또한 중앙정렬인것처럼 안 보이신다면, 다른 방도가 없는것 같습니다.

혹시 다른 방법이 있다면, PR 날려주시면 감사하겠습니다.

관심 가져주셔서 정말 감사합니다🥺
